// Auto-generated from footer.html.
// DO NOT EDIT.

library x_footer_view;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'package:web_ui/web_ui.dart';

class Footer extends WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated.Element __header;
  autogenerated.HeadingElement __e6;
  autogenerated.Template __t;
  
  Footer.forElement(e) : super.forElement(e);
  
  void created_autogenerated() {
    _root = createShadowRoot();
    __t = new autogenerated.Template(_root);
    _root.innerHtml = '''
    <header id="header">
    <h5 id="__e-6"></h5>
    </header>
    ''';
    __header = _root.query('#header');
    __e6 = __header.query('#__e-6');
    var __binding5 = __t.contentBind(() => (footer));
    __e6.nodes.add(__binding5);
    
    __t.create();
  }
  
  void inserted_autogenerated() {
    __t.insert();
  }
  
  void removed_autogenerated() {
    __t.remove();
    __header = __e6 = __t = null;
  }
  
  void composeChildren() {
    super.composeChildren();
    if (_root is! autogenerated.ShadowRoot) _root = this;
  }
  
  /** Original code from the component. */
  
  String footer;
  
  created() {
    footer = "Made by a sadist";
  }
}

void main() {}

