// Auto-generated from header.html.
// DO NOT EDIT.

library header_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;


// Original code
main(){
}

// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;


  var __t = new autogenerated.Template(_root);
  

  __t.create();
  __t.insert();
}
