// Auto-generated from header.html.
// DO NOT EDIT.

library x_header_view;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'package:web_ui/web_ui.dart';

class Header extends WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated.Element __header;
  autogenerated.HeadingElement __e3;
  autogenerated.Template __t;
  
  Header.forElement(e) : super.forElement(e);
  
  void created_autogenerated() {
    _root = createShadowRoot();
    __t = new autogenerated.Template(_root);
    _root.innerHtml = '''
    <header id="header" style="background: orange;">
    <div style="background: orange;">
    <h2 style="background: orange; height: 40px;" id="__e-3"></h2>
    </div>
    </header>
    ''';
    __header = _root.query('#header');
    __e3 = __header.query('#__e-3');
    var __binding2 = __t.contentBind(() => (header));
    __e3.nodes.add(__binding2);
    
    __t.create();
  }
  
  void inserted_autogenerated() {
    __t.insert();
  }
  
  void removed_autogenerated() {
    __t.remove();
    __header = __e3 = __t = null;
  }
  
  void composeChildren() {
    super.composeChildren();
    if (_root is! autogenerated.ShadowRoot) _root = this;
  }
  
  /** Original code from the component. */
  
  String header;
  
  created() {
    this.header = "Sadistic water sounds";
  }
}

void main() {}

