// Auto-generated from water.html.
// DO NOT EDIT.

library x_water_view;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'package:web_ui/web_ui.dart';

import 'package:dartflash/dartflash.dart';

class Water extends WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated.ButtonElement __e4;
  autogenerated.Template __t;
  
  Water.forElement(e) : super.forElement(e);
  
  void created_autogenerated() {
    _root = createShadowRoot();
    __t = new autogenerated.Template(_root);
    _root.innerHtml = '''
    <button id="__e-4">Play</button>
    ''';
    __e4 = _root.query('#__e-4');
    __t.listen(__e4.on.click, ($event) { playSound(); });
    
    __t.create();
  }
  
  void inserted_autogenerated() {
    __t.insert();
  }
  
  void removed_autogenerated() {
    __t.remove();
    __e4 = __t = null;
  }
  
  void composeChildren() {
    super.composeChildren();
    if (_root is! autogenerated.ShadowRoot) _root = this;
  }
  
  /** Original code from the component. */
  
  void playSound() {
    Sound.loadAudio("TapBasin_01.mp3").then((val) {
      val.play(true);
    });
  }
  
  created() {
  }
}

void main() {}

