// Auto-generated from water_sounds.html.
// DO NOT EDIT.

library water_sounds_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'dart:html';

import 'header.dart';
import 'water.dart';


// Original code
void main() {
}

void reverseText(Event event) {
  var text = query("#text").text;
  var buffer = new StringBuffer();
  for (int i = text.length - 1; i >= 0; i--) {
    buffer.add(text[i]);
  }
  query("#text").text = buffer.toString();
}


// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;
  var __e0, __e1;

  var __t = new autogenerated.Template(_root);
  __e0 = _root.query('#__e-0');
  new Header.forElement(__e0);
  __t.component(__e0);
  __e1 = _root.query('#__e-1');
  new Water.forElement(__e1);
  __t.component(__e1);
  

  __t.create();
  __t.insert();
}
